apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailstore
  namespace: tailstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tailstore
  template:
    metadata:
      labels:
        app: tailstore
    spec:
      containers:
        - name: tailstore
          image: bakhtawar375/tailstore:latest
          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
            - name: MYSQL_HOST
              value: database

            - name: MYSQL_USER
              value: root

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD

            - name: MYSQL_DATABASE
              value: tailstore

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 20
