apiVersion: v1
kind: Service
metadata:
  name: tailstore-service
  namespace: tailstore
spec:
  selector:
    app: tailstore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
